//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeternaryProject.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pet_Details
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pet_Details()
        {
            this.Pet_Owner = new HashSet<Pet_Owner>();
            this.Treatement_Details = new HashSet<Treatement_Details>();
        }
    
        public int ID { get; set; }
        public string PetName { get; set; }
        public string BreedName { get; set; }
        public Nullable<bool> Pedegree { get; set; }
        public System.DateTime DateOfBirth { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pet_Owner> Pet_Owner { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Treatement_Details> Treatement_Details { get; set; }
    }
}
