//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeternaryProject.Models.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VetDBEntities : DbContext
    {
        public VetDBEntities()
            : base("name=VetDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Communication_Address> Communication_Address { get; set; }
        public virtual DbSet<Owner> Owners { get; set; }
        public virtual DbSet<Pet_Details> Pet_Details { get; set; }
        public virtual DbSet<Pet_Owner> Pet_Owner { get; set; }
        public virtual DbSet<Treatement_Details> Treatement_Details { get; set; }

        public System.Data.Entity.DbSet<VeternaryProject.Models.ViewModel.AppointmentModel> AppointmentModels { get; set; }
    }
}
